### ISSUE TITLE
The statistics action is still not fixed.

### ISSUE THREAD

**Issue by adityaraute** [eddiejaoude/gh-actions-html-table-generator#23]
Someone please resolve this issue.

```yaml

 statistics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieJaoudeCommunity/gh-action-community/src/statistics@main
        with:
          firebase-key: ${{ secrets.FIREBASE_KEY }}

```

The error is in the last line, in case anyone did not know. 

It has been persisting for at least three months now. Needs to be dealt with ASAP.
